# Generated by Django 5.1.3 on 2024-11-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('average_rating', models.FloatField(null=True)),
                ('rating_number', models.IntegerField(null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('store', models.CharField(max_length=200, null=True)),
                ('details', models.JSONField(null=True)),
                ('parent_asin', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='myapp_produ_title_925620_idx'), models.Index(fields=['average_rating'], name='myapp_produ_average_12c604_idx')],
            },
        ),
    ]
