# Generated by Django 5.1.3 on 2024-11-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_images'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='myapp_produ_title_925620_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='myapp_produ_average_12c604_idx',
        ),
    ]
