# Generated by Django 3.1.12 on 2024-12-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_product_myapp_produ_title_925620_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
    ]
