# Generated by Django 3.1.12 on 2024-12-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20241215_1345'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='sample',
        ),
    ]
