# Generated by Django 3.1.12 on 2024-12-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
